/**
 * Curated symbol and emoji bank for the picker. Each entry carries keywords so
 * the search can match by name, not only by the glyph itself.
 */
export type Glyph = { char: string; name: string };
export type GlyphGroup = { id: string; label: string; glyphs: Glyph[] };

export const GLYPH_GROUPS: GlyphGroup[] = [
  {
    id: "flechas",
    label: "Flechas",
    glyphs: [
      { char: "←", name: "flecha izquierda arrow left" },
      { char: "→", name: "flecha derecha arrow right" },
      { char: "↑", name: "flecha arriba arrow up" },
      { char: "↓", name: "flecha abajo arrow down" },
      { char: "↔", name: "flecha doble horizontal izquierda derecha arrow" },
      { char: "↕", name: "flecha doble vertical arriba abajo arrow" },
      { char: "↖", name: "flecha diagonal arriba izquierda arrow northwest" },
      { char: "↗", name: "flecha diagonal arriba derecha arrow northeast" },
      { char: "↘", name: "flecha diagonal abajo derecha arrow southeast" },
      { char: "↙", name: "flecha diagonal abajo izquierda arrow southwest" },
      { char: "⇐", name: "flecha doble izquierda arrow double left" },
      { char: "⇒", name: "flecha doble derecha arrow double right implica" },
      { char: "⇑", name: "flecha doble arriba arrow double up" },
      { char: "⇓", name: "flecha doble abajo arrow double down" },
      { char: "⇔", name: "equivale doble flecha horizontal arrow" },
      { char: "⇕", name: "flecha doble vertical arrow double" },
      { char: "↩", name: "retorno flecha curva izquierda return" },
      { char: "↪", name: "flecha curva derecha forward" },
      { char: "↺", name: "flecha circular antihorario counterclockwise" },
      { char: "↻", name: "flecha circular horario clockwise rotar" },
      { char: "⟲", name: "flecha giro antihorario refrescar" },
      { char: "⟳", name: "flecha giro horario recargar refresh" },
      { char: "⤴", name: "flecha curva arriba derecha" },
      { char: "⤵", name: "flecha curva abajo derecha" },
      { char: "⟵", name: "flecha larga izquierda long arrow" },
      { char: "⟶", name: "flecha larga derecha long arrow" },
      { char: "⟷", name: "flecha larga doble long arrow" },
      { char: "⟹", name: "flecha larga doble derecha long arrow" },
      { char: "↰", name: "flecha esquina arriba izquierda corner" },
      { char: "↱", name: "flecha esquina arriba derecha corner" },
      { char: "↲", name: "flecha esquina abajo izquierda corner" },
      { char: "↳", name: "flecha esquina abajo derecha corner subnivel" },
      { char: "➜", name: "flecha gruesa derecha arrow bold" },
      { char: "➡", name: "flecha derecha rellena arrow right" },
      { char: "⬅", name: "flecha izquierda rellena arrow left" },
      { char: "⬆", name: "flecha arriba rellena arrow up" },
      { char: "⬇", name: "flecha abajo rellena arrow down" },
      { char: "➤", name: "flecha punta triangulo derecha" },
      { char: "»", name: "flecha doble chevron derecha" },
      { char: "«", name: "flecha doble chevron izquierda" },
    ],
  },
  {
    id: "puntuacion",
    label: "Puntuación y tipografía",
    glyphs: [
      { char: "•", name: "viñeta bullet punto" },
      { char: "◦", name: "viñeta hueca bullet blanco" },
      { char: "‣", name: "viñeta triangular bullet" },
      { char: "·", name: "punto medio middle dot" },
      { char: "…", name: "puntos suspensivos ellipsis" },
      { char: "–", name: "guion en dash medio" },
      { char: "—", name: "raya em dash largo" },
      { char: "―", name: "raya horizontal barra" },
      { char: "‐", name: "guion hyphen" },
      { char: "­", name: "guion suave soft hyphen" },
      { char: "«", name: "comilla angular abre francesa" },
      { char: "»", name: "comilla angular cierra francesa" },
      { char: "“", name: "comilla inglesa abre doble" },
      { char: "”", name: "comilla inglesa cierra doble" },
      { char: "„", name: "comilla baja doble abre" },
      { char: "‘", name: "comilla simple abre" },
      { char: "’", name: "comilla simple cierra apostrofo" },
      { char: "‚", name: "comilla baja simple" },
      { char: "‹", name: "comilla angular simple abre" },
      { char: "›", name: "comilla angular simple cierra" },
      { char: "¿", name: "interrogacion abre pregunta" },
      { char: "?", name: "interrogacion cierra pregunta question" },
      { char: "¡", name: "exclamacion abre admiracion" },
      { char: "!", name: "exclamacion cierra admiracion" },
      { char: "‽", name: "interrobang exclamacion interrogacion" },
      { char: "§", name: "seccion section" },
      { char: "¶", name: "parrafo pilcrow calderon" },
      { char: "†", name: "daga cruz obelisco dagger" },
      { char: "‡", name: "doble daga diesis dagger" },
      { char: "※", name: "referencia asterisco marca" },
      { char: "‾", name: "linea superior overline" },
      { char: "_", name: "guion bajo underscore raya baja" },
      { char: "‗", name: "doble raya baja" },
      { char: "⁂", name: "asterismo tres asteriscos" },
      { char: "❡", name: "parrafo adornado" },
      { char: "⸮", name: "signo ironia interrogacion invertida" },
    ],
  },
  {
    id: "matematicas",
    label: "Matemáticas",
    glyphs: [
      { char: "+", name: "mas suma plus" },
      { char: "−", name: "menos resta minus signo" },
      { char: "×", name: "por multiplicacion times" },
      { char: "÷", name: "division divide" },
      { char: "∕", name: "barra division fraccion slash" },
      { char: "⁄", name: "barra fraccion" },
      { char: "±", name: "mas menos plus minus" },
      { char: "∓", name: "menos mas" },
      { char: "=", name: "igual equals" },
      { char: "≈", name: "aproximado casi igual approx" },
      { char: "≠", name: "distinto no igual not equal" },
      { char: "≡", name: "identico equivalente congruente" },
      { char: "≢", name: "no identico" },
      { char: "≤", name: "menor o igual less equal" },
      { char: "≥", name: "mayor o igual greater equal" },
      { char: "≪", name: "mucho menor que" },
      { char: "≫", name: "mucho mayor que" },
      { char: "<", name: "menor que less than" },
      { char: ">", name: "mayor que greater than" },
      { char: "∞", name: "infinito infinity" },
      { char: "√", name: "raiz cuadrada square root" },
      { char: "∛", name: "raiz cubica cube root" },
      { char: "∜", name: "raiz cuarta" },
      { char: "∑", name: "sumatorio sumatoria sum" },
      { char: "∏", name: "productorio producto product" },
      { char: "∫", name: "integral" },
      { char: "∬", name: "integral doble" },
      { char: "∮", name: "integral contorno" },
      { char: "∂", name: "derivada parcial partial" },
      { char: "∇", name: "nabla gradiente del" },
      { char: "∆", name: "delta incremento" },
      { char: "∈", name: "pertenece elemento de belongs" },
      { char: "∉", name: "no pertenece" },
      { char: "∋", name: "contiene como elemento" },
      { char: "∅", name: "conjunto vacio empty set" },
      { char: "∩", name: "interseccion intersection" },
      { char: "∪", name: "union" },
      { char: "⊂", name: "subconjunto subset" },
      { char: "⊃", name: "superconjunto superset" },
      { char: "⊆", name: "subconjunto o igual" },
      { char: "⊇", name: "superconjunto o igual" },
      { char: "∀", name: "para todo cuantificador universal forall" },
      { char: "∃", name: "existe cuantificador existencial exists" },
      { char: "∄", name: "no existe" },
      { char: "∧", name: "y logico conjuncion and" },
      { char: "∨", name: "o logico disyuncion or" },
      { char: "¬", name: "negacion no logico not" },
      { char: "⊕", name: "suma directa xor circulo" },
      { char: "⊗", name: "producto tensorial circulo" },
      { char: "∴", name: "por lo tanto therefore" },
      { char: "∵", name: "porque because" },
      { char: "∝", name: "proporcional proportional" },
      { char: "∠", name: "angulo angle" },
      { char: "⊥", name: "perpendicular" },
      { char: "∥", name: "paralelo parallel" },
      { char: "°", name: "grado degree" },
      { char: "′", name: "prima minuto pie" },
      { char: "″", name: "doble prima segundo pulgada" },
      { char: "‰", name: "por mil permille" },
      { char: "‱", name: "por diez mil" },
      { char: "%", name: "porcentaje percent" },
      { char: "ℝ", name: "reales conjunto numeros real" },
      { char: "ℕ", name: "naturales conjunto numeros natural" },
      { char: "ℤ", name: "enteros conjunto numeros integer" },
      { char: "ℚ", name: "racionales conjunto numeros" },
      { char: "ℂ", name: "complejos conjunto numeros complex" },
      { char: "½", name: "un medio fraccion mitad half" },
      { char: "⅓", name: "un tercio fraccion" },
      { char: "⅔", name: "dos tercios fraccion" },
      { char: "¼", name: "un cuarto fraccion cuarto" },
      { char: "¾", name: "tres cuartos fraccion" },
      { char: "⅕", name: "un quinto fraccion" },
      { char: "⅛", name: "un octavo fraccion" },
      { char: "⅜", name: "tres octavos fraccion" },
      { char: "∙", name: "punto producto dot" },
      { char: "⋅", name: "punto multiplicacion escalar" },
      { char: "∎", name: "fin demostracion qed cuadrado" },
      { char: "ℵ", name: "aleph cardinalidad infinito" },
    ],
  },
  {
    id: "letras-griegas",
    label: "Letras griegas",
    glyphs: [
      { char: "Α", name: "alfa mayuscula alpha griega" },
      { char: "α", name: "alfa minuscula alpha griega" },
      { char: "Β", name: "beta mayuscula griega" },
      { char: "β", name: "beta minuscula griega" },
      { char: "Γ", name: "gamma mayuscula griega" },
      { char: "γ", name: "gamma minuscula griega" },
      { char: "Δ", name: "delta mayuscula griega" },
      { char: "δ", name: "delta minuscula griega" },
      { char: "Ε", name: "epsilon mayuscula griega" },
      { char: "ε", name: "epsilon minuscula griega" },
      { char: "Ζ", name: "zeta mayuscula griega" },
      { char: "ζ", name: "zeta minuscula griega" },
      { char: "Η", name: "eta mayuscula griega" },
      { char: "η", name: "eta minuscula griega" },
      { char: "Θ", name: "theta mayuscula griega" },
      { char: "θ", name: "theta minuscula griega" },
      { char: "Ι", name: "iota mayuscula griega" },
      { char: "ι", name: "iota minuscula griega" },
      { char: "Κ", name: "kappa mayuscula griega" },
      { char: "κ", name: "kappa minuscula griega" },
      { char: "Λ", name: "lambda mayuscula griega" },
      { char: "λ", name: "lambda minuscula griega" },
      { char: "Μ", name: "mu mayuscula griega" },
      { char: "μ", name: "mu minuscula micro griega" },
      { char: "Ν", name: "nu ny mayuscula griega" },
      { char: "ν", name: "nu ny minuscula griega" },
      { char: "Ξ", name: "xi mayuscula griega" },
      { char: "ξ", name: "xi minuscula griega" },
      { char: "Ο", name: "omicron mayuscula griega" },
      { char: "ο", name: "omicron minuscula griega" },
      { char: "Π", name: "pi mayuscula griega" },
      { char: "π", name: "pi minuscula griega" },
      { char: "Ρ", name: "rho ro mayuscula griega" },
      { char: "ρ", name: "rho ro minuscula griega" },
      { char: "Σ", name: "sigma mayuscula griega" },
      { char: "σ", name: "sigma minuscula griega" },
      { char: "ς", name: "sigma final minuscula griega" },
      { char: "Τ", name: "tau mayuscula griega" },
      { char: "τ", name: "tau minuscula griega" },
      { char: "Υ", name: "upsilon ypsilon mayuscula griega" },
      { char: "υ", name: "upsilon ypsilon minuscula griega" },
      { char: "Φ", name: "phi fi mayuscula griega" },
      { char: "φ", name: "phi fi minuscula griega" },
      { char: "Χ", name: "chi ji mayuscula griega" },
      { char: "χ", name: "chi ji minuscula griega" },
      { char: "Ψ", name: "psi mayuscula griega" },
      { char: "ψ", name: "psi minuscula griega" },
      { char: "Ω", name: "omega mayuscula griega ohmio" },
      { char: "ω", name: "omega minuscula griega" },
    ],
  },
  {
    id: "moneda",
    label: "Moneda",
    glyphs: [
      { char: "€", name: "euro moneda europa" },
      { char: "$", name: "dolar peso moneda dollar" },
      { char: "£", name: "libra esterlina moneda pound" },
      { char: "¥", name: "yen yuan moneda japon china" },
      { char: "¢", name: "centavo cent moneda" },
      { char: "₡", name: "colon moneda costa rica" },
      { char: "₿", name: "bitcoin cripto moneda" },
      { char: "₽", name: "rublo moneda rusia ruble" },
      { char: "₹", name: "rupia india moneda rupee" },
      { char: "₩", name: "won moneda corea" },
      { char: "₪", name: "shekel moneda israel" },
      { char: "₫", name: "dong moneda vietnam" },
      { char: "₴", name: "grivna hryvnia moneda ucrania" },
      { char: "₦", name: "naira moneda nigeria" },
      { char: "₱", name: "peso moneda filipinas" },
      { char: "₲", name: "guarani moneda paraguay" },
      { char: "₵", name: "cedi moneda ghana" },
      { char: "₸", name: "tenge moneda kazajistan" },
      { char: "₺", name: "lira moneda turquia" },
      { char: "₼", name: "manat moneda azerbaiyan" },
      { char: "₾", name: "lari moneda georgia" },
      { char: "﷼", name: "rial moneda arabia iran" },
      { char: "฿", name: "baht moneda tailandia" },
      { char: "₭", name: "kip moneda laos" },
      { char: "₮", name: "tugrik moneda mongolia" },
      { char: "₯", name: "dracma moneda grecia" },
      { char: "₰", name: "pfennig moneda alemania" },
      { char: "₣", name: "franco frances moneda franc" },
      { char: "₤", name: "lira italiana moneda" },
      { char: "₥", name: "milesimo mill moneda" },
      { char: "₧", name: "peseta moneda españa" },
      { char: "¤", name: "moneda generica currency signo" },
      { char: "₠", name: "unidad cuenta europea ecu" },
    ],
  },
  {
    id: "teclado",
    label: "Símbolos técnicos y de teclado",
    glyphs: [
      { char: "⌘", name: "comando command mac tecla cmd" },
      { char: "⌥", name: "opcion option alt mac tecla" },
      { char: "⇧", name: "mayusculas shift tecla" },
      { char: "⌃", name: "control ctrl tecla" },
      { char: "⏎", name: "enter intro retorno return tecla" },
      { char: "↵", name: "enter intro salto linea return" },
      { char: "⌤", name: "enter numerico tecla" },
      { char: "⌫", name: "borrar retroceso backspace delete tecla" },
      { char: "⌦", name: "suprimir delete forward tecla" },
      { char: "⎋", name: "escape esc tecla" },
      { char: "⇪", name: "bloqueo mayusculas caps lock tecla" },
      { char: "⇥", name: "tabulador tab tecla" },
      { char: "⇤", name: "tabulador atras shift tab" },
      { char: "␣", name: "espacio space barra tecla" },
      { char: "⇞", name: "avanzar pagina page up tecla" },
      { char: "⇟", name: "retroceder pagina page down tecla" },
      { char: "↖", name: "inicio home tecla" },
      { char: "↘", name: "fin end tecla" },
      { char: "⌂", name: "casa home directorio inicio" },
      { char: "⎇", name: "alt opcion tecla alternar" },
      { char: "⏏", name: "expulsar eject tecla" },
      { char: "⏻", name: "encendido power boton" },
      { char: "⏼", name: "conmutar power toggle" },
      { char: "⏽", name: "encendido on power" },
      { char: "⭘", name: "apagado off power" },
      { char: "⌨", name: "teclado keyboard" },
      { char: "⎚", name: "borrar pantalla clear" },
      { char: "⌧", name: "cancelar x tecla" },
    ],
  },
  {
    id: "formas",
    label: "Formas y geometría",
    glyphs: [
      { char: "●", name: "circulo relleno negro punto" },
      { char: "○", name: "circulo vacio blanco hueco" },
      { char: "◉", name: "circulo con punto diana" },
      { char: "◎", name: "circulo doble anillo" },
      { char: "◌", name: "circulo punteado" },
      { char: "⬤", name: "circulo grande relleno negro" },
      { char: "◯", name: "circulo grande vacio" },
      { char: "◔", name: "circulo cuarto lleno" },
      { char: "◑", name: "circulo mitad lleno derecha" },
      { char: "◕", name: "circulo tres cuartos lleno" },
      { char: "🔴", name: "circulo rojo" },
      { char: "🟠", name: "circulo naranja" },
      { char: "🟡", name: "circulo amarillo" },
      { char: "🟢", name: "circulo verde" },
      { char: "🔵", name: "circulo azul" },
      { char: "🟣", name: "circulo morado violeta" },
      { char: "⚫", name: "circulo negro medio" },
      { char: "⚪", name: "circulo blanco medio" },
      { char: "■", name: "cuadrado relleno negro" },
      { char: "□", name: "cuadrado vacio blanco hueco" },
      { char: "▪", name: "cuadrado pequeño negro" },
      { char: "▫", name: "cuadrado pequeño blanco" },
      { char: "◼", name: "cuadrado mediano negro" },
      { char: "◻", name: "cuadrado mediano blanco" },
      { char: "▮", name: "rectangulo vertical relleno" },
      { char: "▬", name: "rectangulo horizontal relleno barra" },
      { char: "🟥", name: "cuadrado rojo" },
      { char: "🟧", name: "cuadrado naranja" },
      { char: "🟨", name: "cuadrado amarillo" },
      { char: "🟩", name: "cuadrado verde" },
      { char: "🟦", name: "cuadrado azul" },
      { char: "🟪", name: "cuadrado morado violeta" },
      { char: "▲", name: "triangulo relleno arriba negro" },
      { char: "△", name: "triangulo vacio arriba blanco" },
      { char: "▼", name: "triangulo relleno abajo negro" },
      { char: "▽", name: "triangulo vacio abajo blanco" },
      { char: "◀", name: "triangulo izquierda relleno" },
      { char: "▶", name: "triangulo derecha relleno play" },
      { char: "◁", name: "triangulo izquierda vacio" },
      { char: "▷", name: "triangulo derecha vacio" },
      { char: "◆", name: "diamante rombo relleno negro" },
      { char: "◇", name: "diamante rombo vacio blanco" },
      { char: "◈", name: "diamante con punto" },
      { char: "⬥", name: "diamante grande negro" },
      { char: "⬦", name: "diamante grande blanco" },
      { char: "⬟", name: "pentagono relleno" },
      { char: "⬠", name: "pentagono vacio" },
      { char: "⬢", name: "hexagono relleno" },
      { char: "⬡", name: "hexagono vacio" },
      { char: "⯃", name: "octagono forma" },
      { char: "▰", name: "paralelogramo relleno" },
      { char: "▱", name: "paralelogramo vacio" },
      { char: "◢", name: "triangulo esquina inferior derecha" },
      { char: "◣", name: "triangulo esquina inferior izquierda" },
      { char: "◤", name: "triangulo esquina superior izquierda" },
      { char: "◥", name: "triangulo esquina superior derecha" },
    ],
  },
  {
    id: "estrellas-varios",
    label: "Estrellas y símbolos varios",
    glyphs: [
      { char: "★", name: "estrella llena rellena negra favorito" },
      { char: "☆", name: "estrella vacia hueca blanca" },
      { char: "✦", name: "estrella cuatro puntas brillo" },
      { char: "✧", name: "estrella cuatro puntas vacia" },
      { char: "✩", name: "estrella contorno" },
      { char: "✪", name: "estrella con circulo" },
      { char: "✫", name: "estrella adornada" },
      { char: "✬", name: "estrella seis puntas" },
      { char: "✭", name: "estrella cuerpo negro" },
      { char: "✮", name: "estrella cuerpo esquema" },
      { char: "✯", name: "estrella pivote" },
      { char: "⭐", name: "estrella amarilla favorito" },
      { char: "🌟", name: "estrella brillante destello glowing" },
      { char: "✨", name: "destellos chispas brillo sparkles" },
      { char: "❋", name: "flor asterisco copo pinwheel" },
      { char: "❊", name: "flor ocho petalos" },
      { char: "✳", name: "asterisco ocho puntas" },
      { char: "✴", name: "estrella ocho puntas rellena" },
      { char: "❇", name: "destello chispa" },
      { char: "❈", name: "copo estrella adorno" },
      { char: "✱", name: "asterisco pesado" },
      { char: "✲", name: "asterisco abierto centro" },
      { char: "❄", name: "copo nieve snowflake" },
      { char: "❅", name: "copo nieve estrellado" },
      { char: "❆", name: "copo nieve pesado" },
      { char: "©", name: "copyright derechos autor" },
      { char: "®", name: "marca registrada registered" },
      { char: "™", name: "trademark marca comercial" },
      { char: "℠", name: "marca servicio service mark" },
      { char: "℗", name: "copyright sonido fonograma" },
      { char: "✓", name: "check correcto tick verificado" },
      { char: "✔", name: "check grueso pesado verificado" },
      { char: "✗", name: "cruz error equis x" },
      { char: "✘", name: "cruz pesada error x negrita" },
      { char: "☑", name: "casilla marcada verificada check" },
      { char: "☒", name: "casilla con equis x" },
      { char: "☐", name: "casilla vacia checkbox" },
      { char: "☺", name: "cara sonriente feliz smiley" },
      { char: "☹", name: "cara triste frown" },
      { char: "☯", name: "yin yang equilibrio tao" },
      { char: "☮", name: "paz peace simbolo" },
      { char: "☢", name: "radiactivo radiacion nuclear" },
      { char: "☣", name: "biopeligro biohazard" },
      { char: "⚛", name: "atomo ateo simbolo" },
      { char: "⚠", name: "advertencia peligro warning" },
      { char: "☠", name: "calavera peligro veneno" },
      { char: "✚", name: "cruz griega gruesa" },
      { char: "✝", name: "cruz latina cristiana" },
      { char: "☪", name: "media luna estrella islam" },
      { char: "✡", name: "estrella david judaismo" },
      { char: "☸", name: "rueda dharma budismo" },
      { char: "♻", name: "reciclar reciclaje recycle" },
      { char: "⚡", name: "rayo electricidad relampago" },
      { char: "☀", name: "sol soleado sunny" },
      { char: "☁", name: "nube cloud nublado" },
      { char: "☂", name: "paraguas lluvia umbrella" },
      { char: "☃", name: "muñeco nieve snowman" },
      { char: "☾", name: "luna creciente moon" },
      { char: "☽", name: "luna menguante moon" },
      { char: "⚓", name: "ancla barco marina anchor" },
      { char: "⚖", name: "balanza justicia equilibrio scale" },
      { char: "⚙", name: "engranaje configuracion ajustes gear" },
      { char: "⚜", name: "flor lis fleur adorno heraldica" },
      { char: "❤", name: "corazon negro adorno love" },
      { char: "☘", name: "trebol shamrock suerte irlanda" },
    ],
  },
  {
    id: "ajedrez-cartas",
    label: "Ajedrez y cartas",
    glyphs: [
      { char: "♔", name: "rey blanco ajedrez king" },
      { char: "♕", name: "reina blanca dama ajedrez queen" },
      { char: "♖", name: "torre blanca ajedrez rook" },
      { char: "♗", name: "alfil blanco ajedrez bishop" },
      { char: "♘", name: "caballo blanco ajedrez knight" },
      { char: "♙", name: "peon blanco ajedrez pawn" },
      { char: "♚", name: "rey negro ajedrez king" },
      { char: "♛", name: "reina negra dama ajedrez queen" },
      { char: "♜", name: "torre negra ajedrez rook" },
      { char: "♝", name: "alfil negro ajedrez bishop" },
      { char: "♞", name: "caballo negro ajedrez knight" },
      { char: "♟", name: "peon negro ajedrez pawn" },
      { char: "♠", name: "picas espada carta relleno spade" },
      { char: "♡", name: "corazon carta vacio heart" },
      { char: "♥", name: "corazones carta relleno heart" },
      { char: "♢", name: "diamante carta vacio diamond" },
      { char: "♦", name: "diamantes rombo carta relleno diamond" },
      { char: "♣", name: "treboles carta club" },
      { char: "♤", name: "picas carta vacio spade" },
      { char: "♧", name: "treboles carta vacio club" },
      { char: "🂠", name: "carta reverso dorso baraja" },
      { char: "🃏", name: "comodin joker carta" },
      { char: "🎴", name: "carta flor hanafuda juego" },
    ],
  },
  {
    id: "musica",
    label: "Música",
    glyphs: [
      { char: "♩", name: "negra nota musical quarter" },
      { char: "♪", name: "corchea nota musical eighth" },
      { char: "♫", name: "corcheas notas musicales" },
      { char: "♬", name: "semicorcheas notas musicales beamed" },
      { char: "♭", name: "bemol nota musica flat" },
      { char: "♮", name: "becuadro natural nota musica" },
      { char: "♯", name: "sostenido nota musica sharp" },
      { char: "𝄞", name: "clave sol treble musica" },
      { char: "𝄢", name: "clave fa bass musica" },
      { char: "𝄡", name: "clave do alto musica" },
      { char: "🎵", name: "nota musical emoji" },
      { char: "🎶", name: "notas musicales emoji" },
      { char: "🎼", name: "partitura pentagrama musica" },
      { char: "🎤", name: "microfono cantar karaoke" },
      { char: "🎧", name: "auriculares audifonos cascos" },
      { char: "🎸", name: "guitarra instrumento" },
      { char: "🎹", name: "piano teclado instrumento" },
      { char: "🎺", name: "trompeta instrumento" },
      { char: "🎷", name: "saxofon instrumento" },
      { char: "🥁", name: "tambor bateria instrumento" },
      { char: "🎻", name: "violin instrumento" },
    ],
  },
  {
    id: "numeros-circulados",
    label: "Números y viñetas circulados",
    glyphs: [
      { char: "①", name: "uno circulado numero 1" },
      { char: "②", name: "dos circulado numero 2" },
      { char: "③", name: "tres circulado numero 3" },
      { char: "④", name: "cuatro circulado numero 4" },
      { char: "⑤", name: "cinco circulado numero 5" },
      { char: "⑥", name: "seis circulado numero 6" },
      { char: "⑦", name: "siete circulado numero 7" },
      { char: "⑧", name: "ocho circulado numero 8" },
      { char: "⑨", name: "nueve circulado numero 9" },
      { char: "⑩", name: "diez circulado numero 10" },
      { char: "⓪", name: "cero circulado numero 0" },
      { char: "❶", name: "uno circulo negro numero 1" },
      { char: "❷", name: "dos circulo negro numero 2" },
      { char: "❸", name: "tres circulo negro numero 3" },
      { char: "❹", name: "cuatro circulo negro numero 4" },
      { char: "❺", name: "cinco circulo negro numero 5" },
      { char: "⑴", name: "uno parentesis numero" },
      { char: "⑵", name: "dos parentesis numero" },
      { char: "⑶", name: "tres parentesis numero" },
      { char: "⒈", name: "uno punto numero lista" },
      { char: "⒉", name: "dos punto numero lista" },
      { char: "ⓐ", name: "letra a circulada" },
      { char: "ⓑ", name: "letra b circulada" },
      { char: "ⓒ", name: "letra c circulada" },
      { char: "ⓓ", name: "letra d circulada" },
      { char: "ⓔ", name: "letra e circulada" },
      { char: "Ⓐ", name: "letra a mayuscula circulada" },
      { char: "Ⓑ", name: "letra b mayuscula circulada" },
      { char: "Ⓒ", name: "letra c mayuscula circulada" },
      { char: "⑪", name: "once circulado numero 11" },
      { char: "⑫", name: "doce circulado numero 12" },
      { char: "⑬", name: "trece circulado numero 13" },
      { char: "⑳", name: "veinte circulado numero 20" },
      { char: "🄰", name: "letra a cuadrado" },
      { char: "🅰", name: "letra a cuadrado relleno tipo sangre" },
    ],
  },
  {
    id: "emojis-caras",
    label: "Emojis · Caras y personas",
    glyphs: [
      { char: "😀", name: "sonrisa feliz cara grinning" },
      { char: "😃", name: "sonrisa grande ojos abiertos" },
      { char: "😄", name: "sonrisa dientes ojos felices" },
      { char: "😁", name: "sonrisa dientes radiante" },
      { char: "😆", name: "risa ojos cerrados carcajada" },
      { char: "😅", name: "risa sudor nervioso" },
      { char: "🤣", name: "risa suelo carcajada rodando" },
      { char: "😂", name: "risa llorar lagrimas alegria" },
      { char: "🙂", name: "sonrisa ligera leve" },
      { char: "🙃", name: "cara al reves invertida" },
      { char: "😉", name: "guiño coqueto wink" },
      { char: "😊", name: "sonrisa timida ruborizada feliz" },
      { char: "😇", name: "angel aureola inocente" },
      { char: "🥰", name: "enamorado corazones amor" },
      { char: "😍", name: "ojos corazon amor enamorado" },
      { char: "🤩", name: "estrellas ojos asombro flipando" },
      { char: "😘", name: "beso lanzar mandar" },
      { char: "😗", name: "beso cara silbar" },
      { char: "😋", name: "delicioso rico lengua saborear" },
      { char: "😛", name: "lengua fuera burla" },
      { char: "😜", name: "guiño lengua bromear" },
      { char: "🤪", name: "loco chiflado alocado" },
      { char: "🤨", name: "ceja levantada sospecha duda" },
      { char: "🧐", name: "monoculo curioso examinar" },
      { char: "🤓", name: "nerd empollon gafas" },
      { char: "😎", name: "gafas sol cool genial" },
      { char: "🥳", name: "fiesta celebrar cumpleaños" },
      { char: "🤗", name: "abrazo manos acoger" },
      { char: "🤔", name: "pensando duda reflexion" },
      { char: "🤭", name: "risa mano tapar boca" },
      { char: "🤫", name: "silencio shhh callar secreto" },
      { char: "🤥", name: "mentira pinocho nariz larga" },
      { char: "😐", name: "neutral serio indiferente" },
      { char: "😑", name: "sin expresion inexpresivo" },
      { char: "😶", name: "sin boca callado mudo" },
      { char: "😏", name: "sonrisa picara maliciosa" },
      { char: "😒", name: "desganado harto molesto" },
      { char: "🙄", name: "ojos en blanco fastidio" },
      { char: "😬", name: "mueca dientes apretados incomodo" },
      { char: "😮‍💨", name: "suspiro aliviado resoplar" },
      { char: "😔", name: "pensativo triste abatido" },
      { char: "😪", name: "sueño moco cansado" },
      { char: "😴", name: "durmiendo dormido zzz sueño" },
      { char: "😷", name: "mascarilla enfermo cubrebocas" },
      { char: "🤒", name: "termometro fiebre enfermo" },
      { char: "🤕", name: "venda herido golpe cabeza" },
      { char: "🤢", name: "nausea asco verde vomito" },
      { char: "🤮", name: "vomitar vomito devolver" },
      { char: "🤧", name: "estornudo pañuelo resfriado" },
      { char: "🥵", name: "calor sudor acalorado" },
      { char: "🥶", name: "frio helado congelado" },
      { char: "😵", name: "mareado aturdido espirales" },
      { char: "🤯", name: "explota mente cabeza flipar" },
      { char: "😳", name: "sonrojo verguenza atonito" },
      { char: "🥺", name: "suplicar ojos tiernos pena" },
      { char: "😢", name: "llorar lagrima triste" },
      { char: "😭", name: "llorar mucho sollozo triste" },
      { char: "😤", name: "resoplar enojado orgulloso" },
      { char: "😠", name: "enfadado enojado molesto" },
      { char: "😡", name: "furioso rojo ira rabia" },
      { char: "🤬", name: "insultos palabrotas censura" },
      { char: "😱", name: "grito miedo horror susto" },
      { char: "😨", name: "asustado miedo palido" },
      { char: "😰", name: "ansioso sudor nervioso" },
      { char: "😥", name: "decepcion aliviado triste" },
      { char: "🥴", name: "borracho mareado atontado" },
      { char: "👶", name: "bebe niño recien nacido" },
      { char: "🧒", name: "niño criatura infante" },
      { char: "👦", name: "niño chico muchacho" },
      { char: "👧", name: "niña chica muchacha" },
      { char: "🧑", name: "persona adulto" },
      { char: "👨", name: "hombre señor adulto" },
      { char: "👩", name: "mujer señora adulta" },
      { char: "🧓", name: "anciano mayor viejo persona" },
      { char: "👴", name: "abuelo anciano viejo" },
      { char: "👵", name: "abuela anciana vieja" },
      { char: "👮", name: "policia agente oficial" },
      { char: "👷", name: "obrero construccion trabajador" },
      { char: "🧑‍⚕️", name: "medico doctor enfermero salud" },
      { char: "🧑‍🍳", name: "cocinero chef" },
      { char: "🧑‍🎓", name: "estudiante graduado" },
      { char: "🦸", name: "superheroe heroe" },
      { char: "🦹", name: "villano supervillano" },
      { char: "🧙", name: "mago hechicero brujo" },
      { char: "👻", name: "fantasma boo halloween" },
    ],
  },
  {
    id: "emojis-gestos",
    label: "Emojis · Gestos y manos",
    glyphs: [
      { char: "👍", name: "pulgar arriba like ok bien" },
      { char: "👎", name: "pulgar abajo dislike mal" },
      { char: "👏", name: "aplauso aplaudir palmas" },
      { char: "🙌", name: "manos arriba celebrar alabar" },
      { char: "🙏", name: "rezar gracias por favor manos juntas" },
      { char: "👋", name: "saludo adios hola mano" },
      { char: "✌️", name: "victoria paz dos dedos" },
      { char: "🤝", name: "apreton manos acuerdo trato" },
      { char: "💪", name: "fuerza musculo biceps fuerte" },
      { char: "👌", name: "ok perfecto dedos" },
      { char: "🤌", name: "dedos juntos italiano gesto" },
      { char: "🤏", name: "pellizco poco pequeño" },
      { char: "✊", name: "puño arriba lucha resistencia" },
      { char: "👊", name: "puño golpe choque saludo" },
      { char: "🤛", name: "puño izquierda golpe" },
      { char: "🤜", name: "puño derecha golpe" },
      { char: "🤞", name: "dedos cruzados suerte" },
      { char: "🤟", name: "te quiero mano amor rock" },
      { char: "🤘", name: "cuernos rock metal" },
      { char: "🤙", name: "llamame shaka mano" },
      { char: "👈", name: "señalar izquierda dedo" },
      { char: "👉", name: "señalar derecha dedo" },
      { char: "👆", name: "señalar arriba dedo" },
      { char: "👇", name: "señalar abajo dedo" },
      { char: "☝️", name: "dedo indice arriba uno señalar" },
      { char: "✋", name: "mano alta detener stop palma" },
      { char: "🤚", name: "dorso mano levantada" },
      { char: "🖐️", name: "mano abierta dedos separados" },
      { char: "🖖", name: "saludo vulcano spock" },
      { char: "🤲", name: "manos juntas ofrecer palmas" },
      { char: "🙋", name: "levantar mano preguntar" },
      { char: "🤦", name: "facepalm mano cara verguenza" },
      { char: "🤷", name: "encogerse hombros no se duda" },
      { char: "💅", name: "uñas manicura pintar" },
      { char: "🤳", name: "selfie foto movil" },
    ],
  },
  {
    id: "emojis-animales",
    label: "Emojis · Animales y naturaleza",
    glyphs: [
      { char: "🐶", name: "perro cachorro dog can" },
      { char: "🐱", name: "gato gatito cat michi" },
      { char: "🐭", name: "raton mouse" },
      { char: "🐹", name: "hamster mascota" },
      { char: "🐰", name: "conejo conejito bunny" },
      { char: "🦊", name: "zorro fox" },
      { char: "🐻", name: "oso bear" },
      { char: "🐼", name: "panda oso" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tigre cara tiger" },
      { char: "🦁", name: "leon lion melena" },
      { char: "🐮", name: "vaca cara cow" },
      { char: "🐷", name: "cerdo cochino puerco pig" },
      { char: "🐸", name: "rana sapo frog" },
      { char: "🐵", name: "mono cara monkey" },
      { char: "🐒", name: "mono cuerpo monkey" },
      { char: "🐔", name: "gallina pollo chicken" },
      { char: "🐧", name: "pinguino penguin" },
      { char: "🐦", name: "pajaro ave bird" },
      { char: "🦅", name: "aguila eagle rapaz" },
      { char: "🦉", name: "buho lechuza owl" },
      { char: "🦇", name: "murcielago bat" },
      { char: "🐺", name: "lobo wolf" },
      { char: "🐗", name: "jabali cerdo salvaje boar" },
      { char: "🐴", name: "caballo cara horse" },
      { char: "🦄", name: "unicornio unicorn" },
      { char: "🐝", name: "abeja bee miel" },
      { char: "🐛", name: "gusano oruga bug" },
      { char: "🦋", name: "mariposa butterfly" },
      { char: "🐌", name: "caracol snail baba" },
      { char: "🐞", name: "mariquita catarina ladybug" },
      { char: "🐜", name: "hormiga ant" },
      { char: "🕷️", name: "araña spider" },
      { char: "🦂", name: "escorpion alacran scorpion" },
      { char: "🐢", name: "tortuga turtle" },
      { char: "🐍", name: "serpiente vibora snake" },
      { char: "🦎", name: "lagarto lagartija lizard" },
      { char: "🐙", name: "pulpo octopus" },
      { char: "🦑", name: "calamar squid" },
      { char: "🦐", name: "gamba camaron shrimp" },
      { char: "🦀", name: "cangrejo crab" },
      { char: "🐟", name: "pez fish pescado" },
      { char: "🐠", name: "pez tropical colores fish" },
      { char: "🐡", name: "pez globo fugu" },
      { char: "🐬", name: "delfin dolphin" },
      { char: "🦈", name: "tiburon shark" },
      { char: "🐳", name: "ballena chorro whale" },
      { char: "🐋", name: "ballena grande whale" },
      { char: "🐊", name: "cocodrilo caiman crocodile" },
      { char: "🐘", name: "elefante elephant" },
      { char: "🦒", name: "jirafa giraffe" },
      { char: "🦓", name: "cebra zebra" },
      { char: "🐎", name: "caballo corriendo horse" },
      { char: "🐖", name: "cerdo cuerpo puerco pig" },
      { char: "🐑", name: "oveja borrego sheep" },
      { char: "🐐", name: "cabra goat" },
      { char: "🦌", name: "ciervo venado deer" },
      { char: "🌸", name: "flor cerezo sakura rosa" },
      { char: "🌹", name: "rosa flor roja rose" },
      { char: "🌻", name: "girasol sunflower" },
      { char: "🌷", name: "tulipan flor tulip" },
      { char: "🌵", name: "cactus planta" },
      { char: "🌲", name: "arbol pino conifera evergreen" },
      { char: "🌳", name: "arbol frondoso tree" },
      { char: "🌴", name: "palmera palm arbol" },
      { char: "🍀", name: "trebol cuatro hojas suerte clover" },
      { char: "🍁", name: "hoja arce otoño maple" },
      { char: "🍂", name: "hojas caidas otoño" },
      { char: "🌿", name: "hierba planta ramita herb" },
      { char: "🌱", name: "brote planta semilla germinar" },
    ],
  },
  {
    id: "emojis-comida",
    label: "Emojis · Comida y bebida",
    glyphs: [
      { char: "🍎", name: "manzana roja apple fruta" },
      { char: "🍏", name: "manzana verde apple fruta" },
      { char: "🍐", name: "pera pear fruta" },
      { char: "🍊", name: "naranja mandarina fruta orange" },
      { char: "🍋", name: "limon lemon fruta" },
      { char: "🍌", name: "platano banana fruta" },
      { char: "🍉", name: "sandia watermelon fruta" },
      { char: "🍇", name: "uvas grapes fruta" },
      { char: "🍓", name: "fresa strawberry fruta" },
      { char: "🫐", name: "arandanos blueberries fruta" },
      { char: "🍒", name: "cerezas cherries fruta" },
      { char: "🍑", name: "melocoton durazno peach fruta" },
      { char: "🥭", name: "mango fruta tropical" },
      { char: "🍍", name: "piña ananas pineapple fruta" },
      { char: "🥥", name: "coco coconut fruta" },
      { char: "🥝", name: "kiwi fruta" },
      { char: "🍅", name: "tomate tomato verdura" },
      { char: "🥑", name: "aguacate palta avocado" },
      { char: "🥦", name: "brocoli broccoli verdura" },
      { char: "🥕", name: "zanahoria carrot verdura" },
      { char: "🌽", name: "maiz elote choclo corn" },
      { char: "🌶️", name: "chile picante pimiento pepper" },
      { char: "🥔", name: "patata papa potato" },
      { char: "🍞", name: "pan bread hogaza" },
      { char: "🥐", name: "croissant cuernito" },
      { char: "🥖", name: "baguette pan frances" },
      { char: "🧀", name: "queso cheese" },
      { char: "🥚", name: "huevo egg" },
      { char: "🍳", name: "huevo frito sarten cocina" },
      { char: "🥓", name: "bacon panceta tocino" },
      { char: "🍔", name: "hamburguesa burger" },
      { char: "🍟", name: "papas fritas patatas fries" },
      { char: "🌭", name: "hot dog perrito caliente" },
      { char: "🍕", name: "pizza porcion" },
      { char: "🌮", name: "taco mexicano" },
      { char: "🌯", name: "burrito wrap" },
      { char: "🍝", name: "pasta espagueti spaghetti" },
      { char: "🍜", name: "ramen fideos sopa noodles" },
      { char: "🍣", name: "sushi comida japonesa" },
      { char: "🍤", name: "gamba tempura camaron frito" },
      { char: "🍙", name: "onigiri bola arroz" },
      { char: "🍚", name: "arroz rice bol" },
      { char: "🍦", name: "helado soft cono ice cream" },
      { char: "🍩", name: "dona donut rosquilla" },
      { char: "🍪", name: "galleta cookie" },
      { char: "🎂", name: "tarta pastel cumpleaños cake" },
      { char: "🍰", name: "porcion pastel tarta cake" },
      { char: "🍫", name: "chocolate tableta" },
      { char: "🍬", name: "caramelo dulce candy" },
      { char: "🍭", name: "piruleta chupetin lollipop" },
      { char: "🍯", name: "miel tarro honey" },
      { char: "☕", name: "cafe taza coffee caliente" },
      { char: "🍵", name: "te taza matcha tea" },
      { char: "🧃", name: "zumo jugo caja juice" },
      { char: "🥤", name: "refresco vaso bebida soda" },
      { char: "🍺", name: "cerveza jarra beer" },
      { char: "🍷", name: "vino copa wine" },
      { char: "🍸", name: "coctel martini cocktail" },
      { char: "🥂", name: "brindis copas champan cheers" },
      { char: "🍾", name: "champan botella descorche" },
    ],
  },
  {
    id: "emojis-viajes",
    label: "Emojis · Viajes y lugares",
    glyphs: [
      { char: "🚗", name: "coche auto carro car" },
      { char: "🚕", name: "taxi coche amarillo" },
      { char: "🚙", name: "todoterreno suv coche" },
      { char: "🚌", name: "autobus bus guagua" },
      { char: "🚎", name: "trolebus autobus electrico" },
      { char: "🏎️", name: "coche carreras formula racing" },
      { char: "🚓", name: "coche policia patrulla" },
      { char: "🚑", name: "ambulancia emergencia" },
      { char: "🚒", name: "camion bomberos fire truck" },
      { char: "🚐", name: "furgoneta minibus van" },
      { char: "🚚", name: "camion reparto entrega truck" },
      { char: "🚜", name: "tractor granja agricultura" },
      { char: "🏍️", name: "moto motocicleta motorbike" },
      { char: "🚲", name: "bicicleta bici bike" },
      { char: "🛴", name: "patinete scooter" },
      { char: "🛵", name: "scooter moto vespa" },
      { char: "🚂", name: "tren locomotora vapor train" },
      { char: "🚆", name: "tren train ferrocarril" },
      { char: "🚄", name: "tren bala alta velocidad" },
      { char: "🚇", name: "metro subte subway" },
      { char: "🚊", name: "tranvia tram" },
      { char: "✈️", name: "avion vuelo airplane volar" },
      { char: "🛫", name: "avion despegue takeoff" },
      { char: "🛬", name: "avion aterrizaje landing" },
      { char: "🚁", name: "helicoptero helicopter" },
      { char: "🚀", name: "cohete lanzamiento rocket espacio" },
      { char: "🛸", name: "ovni platillo volante ufo" },
      { char: "⛵", name: "velero barco vela sailboat" },
      { char: "🚤", name: "lancha bote rapido speedboat" },
      { char: "🛳️", name: "crucero barco pasajeros" },
      { char: "⚓", name: "ancla barco marina" },
      { char: "🚢", name: "barco buque ship" },
      { char: "🏠", name: "casa hogar home" },
      { char: "🏡", name: "casa jardin hogar" },
      { char: "🏢", name: "edificio oficina building" },
      { char: "🏥", name: "hospital salud" },
      { char: "🏦", name: "banco bank" },
      { char: "🏨", name: "hotel alojamiento" },
      { char: "🏫", name: "escuela colegio school" },
      { char: "🏰", name: "castillo palacio castle" },
      { char: "🗼", name: "torre tokio landmark" },
      { char: "🗽", name: "estatua libertad nueva york" },
      { char: "🗿", name: "moai estatua isla pascua" },
      { char: "⛰️", name: "montaña mountain cima" },
      { char: "🏔️", name: "montaña nevada pico" },
      { char: "🌋", name: "volcan erupcion volcano" },
      { char: "🏖️", name: "playa sombrilla beach" },
      { char: "🏝️", name: "isla desierta palmera island" },
      { char: "🏜️", name: "desierto arena cactus" },
      { char: "🗺️", name: "mapa mundi world map" },
    ],
  },
  {
    id: "emojis-actividades",
    label: "Emojis · Actividades y objetos",
    glyphs: [
      { char: "⚽", name: "futbol balon soccer pelota" },
      { char: "🏀", name: "baloncesto basket pelota" },
      { char: "🏈", name: "futbol americano pelota" },
      { char: "⚾", name: "beisbol pelota baseball" },
      { char: "🎾", name: "tenis pelota tennis" },
      { char: "🏐", name: "voleibol volei pelota" },
      { char: "🏉", name: "rugby pelota" },
      { char: "🎱", name: "billar bola ocho pool" },
      { char: "🏓", name: "ping pong tenis mesa" },
      { char: "🏸", name: "badminton raqueta" },
      { char: "🥅", name: "porteria arco red goal" },
      { char: "🏒", name: "hockey hielo palo" },
      { char: "🥊", name: "boxeo guante boxing" },
      { char: "🥋", name: "artes marciales karate judo" },
      { char: "⛳", name: "golf bandera hoyo" },
      { char: "🎯", name: "diana dardos objetivo target" },
      { char: "🎳", name: "bolos bowling" },
      { char: "🎣", name: "pesca caña fishing" },
      { char: "🎽", name: "camiseta correr running" },
      { char: "🛹", name: "monopatin skate skateboard" },
      { char: "🏆", name: "trofeo copa ganador trophy" },
      { char: "🥇", name: "medalla oro primero gold" },
      { char: "🥈", name: "medalla plata segundo silver" },
      { char: "🥉", name: "medalla bronce tercero bronze" },
      { char: "🎮", name: "videojuego mando control gaming" },
      { char: "🕹️", name: "joystick palanca arcade" },
      { char: "🎲", name: "dado dice azar juego" },
      { char: "🧩", name: "puzzle rompecabezas pieza" },
      { char: "♟️", name: "ajedrez peon juego" },
      { char: "🎨", name: "arte paleta pintura artista" },
      { char: "🖌️", name: "pincel pintar brush" },
      { char: "🖍️", name: "crayon cera pintar" },
      { char: "✏️", name: "lapiz pencil escribir" },
      { char: "✒️", name: "pluma estilografica escribir" },
      { char: "🖊️", name: "boligrafo pluma pen" },
      { char: "📷", name: "camara foto camera fotografia" },
      { char: "📸", name: "camara flash foto" },
      { char: "🎥", name: "camara cine pelicula filmar" },
      { char: "🎬", name: "claqueta cine accion clapper" },
      { char: "🎤", name: "microfono cantar mic" },
      { char: "🎸", name: "guitarra musica instrumento" },
      { char: "🎹", name: "piano teclado musica" },
      { char: "🎺", name: "trompeta musica instrumento" },
      { char: "🥁", name: "tambor bateria musica drum" },
      { char: "🎻", name: "violin musica instrumento" },
      { char: "🎷", name: "saxofon musica instrumento" },
      { char: "🎁", name: "regalo caja present gift" },
      { char: "🎈", name: "globo fiesta balloon" },
      { char: "🎊", name: "confeti bola fiesta" },
      { char: "🎉", name: "fiesta confeti celebrar party" },
      { char: "🔑", name: "llave key abrir" },
      { char: "🔒", name: "candado cerrado bloqueado lock" },
      { char: "🔓", name: "candado abierto desbloqueado unlock" },
      { char: "🔦", name: "linterna luz flashlight" },
      { char: "🕯️", name: "vela candle luz" },
      { char: "🧭", name: "brujula compass norte" },
      { char: "⏳", name: "reloj arena tiempo hourglass" },
      { char: "⌛", name: "reloj arena vacio tiempo" },
      { char: "⏰", name: "despertador alarma reloj" },
      { char: "🔔", name: "campana notificacion bell" },
    ],
  },
  {
    id: "emojis-tecnologia",
    label: "Emojis · Tecnología y oficina",
    glyphs: [
      { char: "💻", name: "portatil laptop ordenador computadora" },
      { char: "🖥️", name: "ordenador escritorio monitor pc" },
      { char: "📱", name: "movil celular telefono smartphone" },
      { char: "☎️", name: "telefono fijo phone" },
      { char: "📞", name: "auricular telefono llamada" },
      { char: "⌨️", name: "teclado keyboard escribir" },
      { char: "🖱️", name: "raton mouse ordenador" },
      { char: "🖨️", name: "impresora printer imprimir" },
      { char: "🖲️", name: "trackball bola control" },
      { char: "💽", name: "minidisco disco md" },
      { char: "💾", name: "disquete guardar save floppy" },
      { char: "💿", name: "cd disco compacto optico" },
      { char: "📀", name: "dvd disco optico" },
      { char: "🔌", name: "enchufe cargador plug electricidad" },
      { char: "🔋", name: "bateria pila battery carga" },
      { char: "🪫", name: "bateria baja poca carga" },
      { char: "💡", name: "bombilla idea luz light" },
      { char: "🔦", name: "linterna luz portatil" },
      { char: "📡", name: "antena satelite parabolica" },
      { char: "📺", name: "television tele tv" },
      { char: "📻", name: "radio emisora" },
      { char: "🎙️", name: "microfono estudio podcast" },
      { char: "⏱️", name: "cronometro stopwatch tiempo" },
      { char: "⏲️", name: "temporizador timer reloj" },
      { char: "🕰️", name: "reloj chimenea antiguo clock" },
      { char: "📆", name: "calendario fecha calendar" },
      { char: "📅", name: "calendario dia agenda" },
      { char: "📇", name: "fichero tarjetero indice rolodex" },
      { char: "📁", name: "carpeta folder archivo" },
      { char: "📂", name: "carpeta abierta folder" },
      { char: "📄", name: "documento hoja pagina file" },
      { char: "📋", name: "portapapeles clipboard tabla" },
      { char: "📎", name: "clip sujetapapeles paperclip" },
      { char: "✂️", name: "tijeras cortar scissors" },
      { char: "🖇️", name: "clips unidos enlazados" },
      { char: "📌", name: "chincheta fijar pin marcar" },
      { char: "📍", name: "pin ubicacion mapa location" },
      { char: "🔍", name: "lupa buscar zoom search" },
      { char: "🔎", name: "lupa derecha buscar zoom" },
    ],
  },
  {
    id: "emojis-simbolos",
    label: "Emojis · Símbolos y corazones",
    glyphs: [
      { char: "❤️", name: "corazon rojo amor love" },
      { char: "🧡", name: "corazon naranja amor" },
      { char: "💛", name: "corazon amarillo amor" },
      { char: "💚", name: "corazon verde amor" },
      { char: "💙", name: "corazon azul amor" },
      { char: "💜", name: "corazon morado violeta amor" },
      { char: "🖤", name: "corazon negro amor" },
      { char: "🤍", name: "corazon blanco amor" },
      { char: "🤎", name: "corazon marron cafe amor" },
      { char: "💔", name: "corazon roto partido heartbreak" },
      { char: "❣️", name: "corazon exclamacion" },
      { char: "💕", name: "dos corazones amor" },
      { char: "💞", name: "corazones giratorios amor" },
      { char: "💓", name: "corazon latiendo pulso" },
      { char: "💗", name: "corazon creciendo amor" },
      { char: "💖", name: "corazon brillante destellos" },
      { char: "💘", name: "corazon flecha cupido flechado" },
      { char: "💝", name: "corazon lazo regalo" },
      { char: "💟", name: "decoracion corazon" },
      { char: "❤️‍🔥", name: "corazon en llamas fuego amor" },
      { char: "❤️‍🩹", name: "corazon curado vendado" },
      { char: "💯", name: "cien perfecto nota 100" },
      { char: "💢", name: "enfado ira simbolo enojo" },
      { char: "💥", name: "explosion choque boom colision" },
      { char: "💫", name: "estrella mareo destello dizzy" },
      { char: "💦", name: "gotas sudor agua salpicar" },
      { char: "💨", name: "viento humo correr rapido" },
      { char: "🕳️", name: "agujero hoyo hole" },
      { char: "💬", name: "bocadillo dialogo comentario chat" },
      { char: "💭", name: "pensamiento nube bocadillo" },
      { char: "🗯️", name: "bocadillo enfado ira grito" },
      { char: "♈", name: "aries zodiaco horoscopo" },
      { char: "♉", name: "tauro zodiaco horoscopo" },
      { char: "♊", name: "geminis zodiaco horoscopo" },
      { char: "♋", name: "cancer zodiaco horoscopo" },
      { char: "♌", name: "leo zodiaco horoscopo" },
      { char: "♍", name: "virgo zodiaco horoscopo" },
      { char: "♎", name: "libra zodiaco horoscopo balanza" },
      { char: "♏", name: "escorpio zodiaco horoscopo" },
      { char: "♐", name: "sagitario zodiaco horoscopo" },
      { char: "♑", name: "capricornio zodiaco horoscopo" },
      { char: "♒", name: "acuario zodiaco horoscopo" },
      { char: "♓", name: "piscis zodiaco horoscopo" },
      { char: "⛎", name: "ofiuco serpentario zodiaco" },
      { char: "🔴", name: "punto rojo circulo" },
      { char: "🟢", name: "punto verde circulo online" },
      { char: "🔵", name: "punto azul circulo" },
      { char: "✅", name: "check verde hecho listo done" },
      { char: "❌", name: "cruz roja error mal x" },
      { char: "❎", name: "cruz verde cuadrado" },
      { char: "➕", name: "mas suma plus boton" },
      { char: "➖", name: "menos resta minus boton" },
      { char: "➗", name: "division boton" },
      { char: "✖️", name: "multiplicacion por boton x" },
      { char: "♾️", name: "infinito infinity emoji" },
      { char: "‼️", name: "doble exclamacion admiracion" },
      { char: "⁉️", name: "exclamacion interrogacion" },
      { char: "❓", name: "interrogacion pregunta roja" },
      { char: "❗", name: "exclamacion admiracion roja" },
      { char: "💤", name: "sueño dormir zzz" },
      { char: "🚫", name: "prohibido no permitido" },
      { char: "⛔", name: "prohibido paso entrada no" },
      { char: "♻️", name: "reciclar reciclaje verde recycle" },
      { char: "⚠️", name: "advertencia peligro warning atencion" },
    ],
  },
  {
    id: "emojis-banderas",
    label: "Emojis · Banderas",
    glyphs: [
      { char: "🏁", name: "bandera cuadros meta carrera finish" },
      { char: "🚩", name: "bandera roja triangular marcar" },
      { char: "🏴", name: "bandera negra" },
      { char: "🏳️", name: "bandera blanca rendicion" },
      { char: "🏳️‍🌈", name: "bandera arcoiris orgullo lgbt pride" },
      { char: "🏴‍☠️", name: "bandera pirata calavera" },
      { char: "🇪🇸", name: "españa bandera spain" },
      { char: "🇲🇽", name: "mexico bandera mexicana" },
      { char: "🇦🇷", name: "argentina bandera" },
      { char: "🇨🇴", name: "colombia bandera" },
      { char: "🇨🇱", name: "chile bandera" },
      { char: "🇵🇪", name: "peru bandera" },
      { char: "🇻🇪", name: "venezuela bandera" },
      { char: "🇺🇸", name: "estados unidos usa bandera america" },
      { char: "🇬🇧", name: "reino unido inglaterra bandera uk" },
      { char: "🇫🇷", name: "francia bandera france" },
      { char: "🇩🇪", name: "alemania bandera germany" },
      { char: "🇮🇹", name: "italia bandera italy" },
      { char: "🇵🇹", name: "portugal bandera" },
      { char: "🇧🇷", name: "brasil bandera brazil" },
      { char: "🇯🇵", name: "japon bandera japan" },
      { char: "🇨🇳", name: "china bandera" },
      { char: "🇰🇷", name: "corea sur bandera korea" },
      { char: "🇮🇳", name: "india bandera" },
      { char: "🇨🇦", name: "canada bandera" },
      { char: "🇦🇺", name: "australia bandera" },
      { char: "🇷🇺", name: "rusia bandera russia" },
      { char: "🇪🇺", name: "union europea bandera europa" },
    ],
  },
];
